#!/usr/bin/python3
#  coding=utf-8
from sys import argv, exit, stderr
import os

PORT=1194
def check(hostname):
    try:
        response = os.system("ping -c 1 -W 2 " + hostname + " > /dev/null 2>&1") # -t 3 нужно ли?
        print(response)
        if response == 0:
            print("ok")
            return(101)
        print("Host unreachable")
        return(104)
    except:
        print("Host unreachable")
        return(104)


def put(hostname, flag):
    print("PUT")
def get(hostname, flag):
    print("GET")
if __name__ == '__main__':
    if len(argv) > 1:
        if argv[1] == "check":
            if len(argv) > 2:
                exit(check(argv[2]))
        elif argv[1] == "put":
            if len(argv) > 3:
                exit(put(argv[2], argv[3]))
        elif argv[1] == "get":
            if len(argv) > 3:
                exit(get(argv[2], argv[3]))
    exit(110)
